{{- if not .Values.objectStorage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cubestore-pvc
spec:
  storageClassName: standard-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}