apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cubestore-worker
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
{{- end }}
spec:
  serviceName: cubestore-worker
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.cubestoreWorker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      cubejsApp: cubestoreWorker
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        cubejsApp: cubestoreWorker
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if not .Values.objectStorage.enabled }}
      volumes:
        - name: cubestore-pv
          persistentVolumeClaim:
            claimName: cubestore-pvc
      {{- end }}
      initContainers:
        - name: init-router
          image: busybox
          command:
            - sh
            - -c
            - >-
              until nc -z cubestore-router {{ .Values.cubestoreRouter.service.port }};
              do echo "Waiting for cubestore-router:{{ .Values.cubestoreRouter.service.port }}"; sleep 3;
              done
      containers:
        - name: cubestore-worker
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CUBESTORE_SERVER_NAME
            value: "$(POD_NAME).cubestore-worker:{{ .Values.cubestoreWorker.service.port }}"
          - name: CUBESTORE_WORKERS
            value: {{ $count := .Values.cubestoreWorker.replicas | int }}{{- $port := .Values.cubestoreWorker.service.port -}}
              {{- $workers := list -}}{{- range until $count -}}{{- $workers = append $workers (printf "cubestore-worker-%d.cubestore-worker:%v" . $port) -}}{{- end -}}
              {{ join "," $workers }}
          envFrom:
          - configMapRef:
              name: {{ .Values.cubestoreWorker.configmap.name }}
          {{- if .Values.objectStorage.enabled }}
          - secretRef:
              name: {{ if .Values.objectStorage.credentials.existingSecret }}{{ .Values.objectStorage.credentials.existingSecret }}{{ else }}cubestore-objectstorage-secret{{ end }}
          {{- end }}
          {{- if not .Values.objectStorage.enabled }}
          volumeMounts:
            - mountPath: /cube/data
              name: cubestore-pv
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.cubestoreWorker.image }}"
          imagePullPolicy: {{ .Values.cubestoreWorker.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.cubestoreWorker.service.port }}
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
