apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cubestore-router
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
{{- end }}
spec:
  serviceName: cubestore-router
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.cubestoreRouter.replicas }}
  {{- end }}
  selector:
    matchLabels:
      cubejsApp: cubestoreRouter
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        cubejsApp: cubestoreRouter
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cubestore-pv
          persistentVolumeClaim:
            claimName: cubestore-pvc
      containers:
        - name: cubestore-router
          env:
          - name: CUBESTORE_WORKERS
            value: {{ $count := .Values.cubestoreWorker.replicas | int }}{{- $port := .Values.cubestoreWorker.service.port -}}
              {{- $workers := list -}}{{- range until $count -}}{{- $workers = append $workers (printf "cubestore-worker-%d.cubestore-worker:%v" . $port) -}}{{- end -}}
              {{ join "," $workers }}
          envFrom:
          - configMapRef:
              name: {{ .Values.cubestoreRouter.configmap.name }}
          command: ["/bin/sh", "-c"]
          args: ["unset CUBESTORE_WORKER_PORT; ./cubestored"]
          volumeMounts:
            - mountPath: /cube/data
              name: cubestore-pv
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.cubestoreRouter.image }}"
          imagePullPolicy: {{ .Values.cubestoreRouter.pullPolicy }}
          ports:
            - name: meta
              containerPort: {{ .Values.cubestoreRouter.service.port }}
              protocol: TCP
            - name: http
              containerPort: 3030
              protocol: TCP
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
